# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170926_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='todo_list',
            new_name='user',
        ),
    ]
