# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170926_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
