# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='docfile',
        ),
    ]
