# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171001_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('p', 'pending'), ('s', 'success')], default='p', max_length=50),
        ),
    ]
